---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-app
  namespace: default
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: "manthesh/java-app-1.0"
        ports:
          - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: manthesh/java-app-1.0
  namespace: default
spec:
  selector:
    app: manthesh/java-app-1.0
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 9001
    port: 8090
